jj = int(input())
tb = int(input())
phi = 22/7
v = phi*jj*jj*tb
l = (2*phi*jj*(jj+tb))
k = (2*phi*jj)
print("Volume = %.2f" %v)
print("Luas = %.2f" %l)
print("Keliling = %.2f\n" %k)

jj1,tb1 = input(). split()
jj1 = int(jj1)
tb1 = int(tb1)
phi1 = 22/7
v1 = phi1*jj1*jj1*tb1
l1 = (2*phi1*jj1*(jj1+tb1))
k1 = (2*phi1*jj1)
print("Volume = %.2f" %v1)
print("Luas = %.2f" %l1)
print("Keliling = %.2f\n" %k1)
