nama = input("Nama                   :")
nim  = input("NIM                    :")
kp   = input("Kelas Praktikum        :")
ttl  = input("Tempat/Tanggal Lahir   :")
alm  = input("Alamat                 :")
hb   = input("Hobby                  :")
nhp  = input("No. HP                 :")
print("\nNama                     :", nama)
print("NIM                      :", nim)
print("Kelas Praktikum          :", kp)
print("Tempat/Tanggal Lahir     :", ttl)
print("Alamat                   :", alm)
print("Hobby                    :", hb)
print("No. HP                   :", nhp)
